name:                TP01
version:             1.21.8.9
author:              "Miguel Montes"
maintainer:          "mmontes@iua.edu.ar"
copyright:           "2018 Miguel Montes"

extra-source-files:
- README.md
- ChangeLog.md

description:         Trabajo Práctico 1

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  TP01:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TP01
    when:
    - condition: false
      other-modules: Paths_TP01

tests:
  TP01-test:
    main:                Spec.hs
    source-dirs:         test/unit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TP01
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2
    - QuickCheck
    - HUnit
    - deepseq
  TP01-doctests:
    main:               doctests.hs
    source-dirs:        test/doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest
