name:                TP02
version:             1.21.8.9
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Trabajo Práctico 2

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  TP02:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TP02
    when:
    - condition: false
      other-modules: Paths_TP02

tests:
  TP02-test:
    main:                Spec.hs
    source-dirs:         test/unit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TP02
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2
    - QuickCheck
    - HUnit
    - HUnit-approx
    - quickcheck-assertions
  TP02-doctest:
    main:                doctests.hs
    source-dirs:         test/doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest
