name:                TP06
version:             1.21.8.10
author:              "Miguel Montes"
maintainer:          "mmontes@iua.edu.ar"
copyright:           "2018 Miguel Montes"

extra-source-files:
- README.md
- ChangeLog.md

description:         Trabajo práctico 6

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  TP06:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TP06
    when:
    - condition: false
      other-modules: Paths_TP06

tests:
  TP06-test:
    main:                Spec.hs
    source-dirs:         test/unit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TP06
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2
    - QuickCheck
    - HUnit
    - HUnit-approx
    - quickcheck-assertions
  TP06-doctest:
    main:                doctests.hs
    source-dirs:         test/doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest
