name:                TP04
version:             1.21.8.10
author:              "Miguel Montes"
maintainer:          "miguel.montes@gmail.com"
copyright:           "2018 Miguel Montes"

extra-source-files:
- README.md
- ChangeLog.md

description:         Trabajo Práctico 4

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  TP04:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TP04
    when:
    - condition: false
      other-modules: Paths_TP04

tests:
  TP04-test:
    main:                Spec.hs
    source-dirs:         test/unit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TP04
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2
    - QuickCheck
    - HUnit
    - HUnit-approx
    - quickcheck-assertions
  TP04-doctest:
    main:                doctests.hs
    source-dirs:         test/doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest
